# Generated by Django 5.0.3 on 2024-05-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="id",
        ),
        migrations.RemoveField(
            model_name="source",
            name="visits",
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Via",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visits", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.ForeignKey(
                        default="direct",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="utm_tracker.source",
                    ),
                ),
            ],
        ),
    ]
