# Generated by Django 5.0.3 on 2024-05-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm_tracker", "0002_remove_source_id_remove_source_visits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="via",
            name="default",
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
