# Generated by Django 5.0.3 on 2024-05-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm_tracker", "0004_alter_via_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="via",
            name="default",
        ),
        migrations.AlterField(
            model_name="via",
            name="source",
            field=models.ForeignKey(
                default="direct",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="utm_tracker.source",
            ),
        ),
    ]
