# Generated by Django 5.0.3 on 2024-05-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm_tracker", "0005_remove_via_default_alter_via_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="via",
            name="source",
            field=models.OneToOneField(
                default="direct",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="utm_tracker.source",
            ),
        ),
    ]
