# Generated by Django 5.0.3 on 2024-05-29 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm_tracker", "0006_alter_via_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Site Hit",
                "verbose_name_plural": "Site Hits",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Traffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visits", models.PositiveIntegerField(default=0)),
                ("last_visit", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.OneToOneField(
                        default="direct",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="utm_tracker.source",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Traffic",
                "ordering": ["-last_visit"],
            },
        ),
        migrations.DeleteModel(
            name="Via",
        ),
    ]
