# Generated by Django 5.0.3 on 2024-06-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm_tracker", "0007_sitehit_traffic_delete_via"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitehit",
            name="http_from",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="traffic",
            name="http_from",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
