# Generated by Django 5.0.3 on 2024-06-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm_tracker", "0008_sitehit_http_from_traffic_http_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitehit",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="traffic",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
