# Generated by Django 5.0.3 on 2024-06-18 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm_tracker", "0012_sitehit_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitehit",
            name="http_from",
            field=models.CharField(
                blank=True,
                help_text="HTTP 'From' header of the site hit request.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitehit",
            name="http_referer",
            field=models.URLField(
                blank=True,
                help_text="HTTP 'Referer' header of the site hit request.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitehit",
            name="ip_address",
            field=models.GenericIPAddressField(help_text="IP address of the site hit."),
        ),
        migrations.AlterField(
            model_name="sitehit",
            name="source",
            field=models.ForeignKey(
                blank=True,
                default="direct",
                help_text="Source of the site hit.",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="utm_tracker.source",
            ),
        ),
        migrations.AlterField(
            model_name="sitehit",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the site hit was recorded."
            ),
        ),
        migrations.AlterField(
            model_name="sitehit",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="User-Agent string of the site hit request.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(
                help_text="Unique name of the traffic source.",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="http_from",
            field=models.CharField(
                blank=True,
                help_text="HTTP 'From' header of the request.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="http_referer",
            field=models.URLField(
                blank=True, help_text="HTTP 'Referer' header of the request.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address of the visitor.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="last_visit",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp of the last visit."
            ),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="source",
            field=models.OneToOneField(
                default="direct",
                help_text="Associated traffic source.",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="utm_tracker.source",
            ),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="User-Agent string of the visitor's browser.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="visits",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of visits recorded."
            ),
        ),
    ]
