# Generated by Django 5.0.3 on 2024-06-20 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "utm_tracker",
            "0013_alter_sitehit_http_from_alter_sitehit_http_referer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitehit",
            name="http_from",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sitehit",
            name="http_referer",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitehit",
            name="ip_address",
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name="sitehit",
            name="source",
            field=models.ForeignKey(
                blank=True,
                default="direct",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="utm_tracker.source",
            ),
        ),
        migrations.AlterField(
            model_name="sitehit",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sitehit",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="http_from",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="http_referer",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="last_visit",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="utm_tracker.source"
            ),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="visits",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
