# Generated by Django 4.1.2 on 2023-05-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_alter_channel_channel_id_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='release_year',
            field=models.IntegerField(default=2023),
        ),
    ]
