# Generated by Django 4.2.1 on 2023-05-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_alter_video_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
