# Generated by Django 4.1.2 on 2023-05-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0010_channel_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='username',
            new_name='handle',
        ),
    ]
