# Generated by Django 4.1.2 on 2023-05-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0011_rename_username_channel_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FilePathField(blank=True, match='^.+\\.(mkv|mp4)$', null=True, path='/home/atharvnaik/Desktop/Movies/'),
        ),
    ]
