# Generated by Django 4.1.2 on 2023-05-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0012_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subtitle',
            field=models.FilePathField(blank=True, match='^.+\\.(vtt|srt)$', null=True, path='/home/atharvnaik/Desktop/Movies/', recursive=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FilePathField(blank=True, match='^.+\\.(mkv|mp4)$', null=True, path='/home/atharvnaik/Desktop/Movies/', recursive=True),
        ),
    ]
