# Generated by Django 4.1.2 on 2023-06-08 22:57

from django.db import migrations, models
import play.validators


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0017_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[play.validators.validate_video_file]),
        ),
    ]
