# Generated by Django 4.1.2 on 2023-06-27 13:52

from django.db import migrations, models
import play.models
import play.validators


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0018_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=play.models.getVideoUploadPath, validators=[play.validators.validate_video_file]),
        ),
    ]
