# Generated by Django 4.1.2 on 2023-07-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0021_alter_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='percentage_watched',
            field=models.FloatField(default=0),
        ),
    ]
