# Generated by Django 4.1.2 on 2023-08-29 17:29

from django.db import migrations, models
import play.models
import play.validators


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0023_history_channel_alter_channel_handle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-last_viewed'], 'verbose_name_plural': 'Histories'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='preview_images',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Historical', 'Historical'), ('Historical Fiction', 'Historical Fiction'), ('Philosophical', 'Philosophical'), ('Political', 'Political'), ('Documentary', 'Documentary'), ('Biographical', 'Biographical'), ('Educational', 'Educational'), ('Musical', 'Musical'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(blank=True, choices=[('eng', 'English'), ('hin', 'Hindi'), ('jap', 'Japanese'), ('kor', 'Korean'), ('oth', 'Other')], default='eng', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='release_year',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='video',
            name='series_episode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='series_season',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitle',
            field=models.FileField(blank=True, null=True, upload_to=play.models.getSubtitleUploadPath, validators=[play.validators.validate_subtitle_file]),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=play.models.getThumbnailUploadPath, validators=[play.validators.validate_upload_image_file]),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('series', True), _negated=True), models.Q(('series_name', None), _negated=True), _connector='OR'), name='series_name_not_null'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('series', True), _negated=True), models.Q(('series_season', None), _negated=True), _connector='OR'), name='series_season_not_null'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('series', True), _negated=True), models.Q(('series_episode', None), _negated=True), _connector='OR'), name='series_episode_not_null'),
        ),
    ]
