# Generated by Django 4.1.2 on 2023-08-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0025_remove_channel_profile_picture_channel_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitles_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Anime', 'Anime'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Historical', 'Historical'), ('Historical Fiction', 'Historical Fiction'), ('Philosophical', 'Philosophical'), ('Political', 'Political'), ('Documentary', 'Documentary'), ('Biographical', 'Biographical'), ('Educational', 'Educational'), ('Musical', 'Musical'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
