# Generated by Django 4.1.2 on 2023-09-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0026_video_subtitles_available_video_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
