# Generated by Django 4.1.2 on 2023-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0027_alter_video_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="views",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="View",
        ),
    ]
