# Generated by Django 5.0.3 on 2024-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0028_video_views_delete_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="release_year",
            field=models.PositiveSmallIntegerField(default=2024),
        ),
    ]
