# Generated by Django 5.0.3 on 2024-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0029_alter_video_release_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="stream_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="video_location",
            field=models.CharField(
                choices=[("local", "local"), ("s3", "s3")],
                default="local",
                max_length=100,
            ),
        ),
    ]
